#!/bin/bash

echo "Installing QEMU emulators on docker-hub build node for multi-arch build process"
docker run --privileged --rm tonistiigi/binfmt --install all

echo "Creating multi-arch builder ahead of build process..."
docker buildx create \
--name multiarch \
--driver docker-container \
--platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
--bootstrap \
--use

